### PR TITLE
GitHub Action to use codespell to find typos

### PR DESCRIPTION
**Pull request by cclauss**
https://github.com/codespell-project/codespell

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
Does this support any other languages besides English?

**Comment by Panquesito7** [comment]
@cclauss, ping.

**Comment by cclauss** [comment]
What is the ping for?

I cannot approve my own PR so I am waiting for other maintainers to review this PR before it can land.

**Review by Panquesito7 — APPROVED** [review]
Thank you, @cclauss. 😄👍

**Comment by Panquesito7** [comment]
I'll merge in a few days if there are no objections.

**Review by vbrazo — APPROVED** [review]
LGTM

**Pull request merged**
