### PR TITLE
Added Gradient Boosting Classifier Explanation

### PR DESCRIPTION
**Pull request by SannketNikam**
### Description

Explanation for [Gradient Boosting Classifier](https://github.com/TheAlgorithms/Python/blob/master/machine_learning/gradient_boosting_classifier.py)

### Checklist

- [x] A description of the changes in this PR is mentioned above.
- [x] All the new and existing checks pass.
- [x] No plagiarized, duplicated, or repetitive documentation that has been directly copied from another source.
- [x] If it's a new explanation, it contains solid, understandable, and accessible information.
- [x] I have read the whole [contributing guidelines](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/CONTRIBUTING.md) and agree to the [Code of Conduct](https://github.com/TheAlgorithms/.github/blob/master/CODE_OF_CONDUCT.md).

### Note to reviewers
This is a explanation for Gradient Boosting Classifier Machine Learning Algorithm implemented by me [here](https://github.com/TheAlgorithms/Python/blob/master/machine_learning/gradient_boosting_classifier.py).

### CODE REVIEW

**Comment by SannketNikam** [comment]
Please review this: @Panquesito7 @appgurueu @vbrazo

**Review by appgurueu — COMMENTED** [review]
I'm afraid this probably isn't a good fit for this repo. This repo ought to consist of clear explanations of clear algorithms, which solve clear problems and have clear time & space complexity bounds.

This explanation however is unfortunately pretty vague. Many terms aren't explained and formalized properly; the example just shows how to use an existing implementation. It doesn't help that it's also quite a bit disorganized.

This *could* be formalized properly, but such a lengthy explanation would vastly exceed the scope of this project.

**Comment by SannketNikam** [comment]
Sure @appgurueu, I will make the necessary changes in the explanation.

**Comment by SannketNikam** [comment]
> Sure @appgurueu, I will make the necessary changes in the explanation.

I have made the changes, could [you](@appgurueu) please review it now

**Comment by appgurueu** [comment]
> I have made the changes, could [you](@appgurueu) please review it now

I'm afraid you misunderstood me. I don't think this is suitable (or likely to eventually become suitable) for inclusion.

> *This explanation however is unfortunately pretty vague. Many terms aren't explained and formalized properly*; the example just shows how to use an existing implementation. [which you also haven't addressed]
> This could be formalized properly, but *such a lengthy explanation would vastly exceed the scope of this project.*

Maybe such a rough "overview" fits somewhere else. Good luck!

**Pull request closed without merging**
