### PR TITLE
Fix Java broken links

### PR DESCRIPTION
**Pull request by alaanescobedo**
HI! I open this PR in relation to this issue: #154 

I know that there is already an open PR in #156, but it is more than 2 months old, so I had doubts about opening it.
I can find other broken links and fix them, but thought I'd leave this PR with just the Java links.

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍

**Comment by alaanescobedo** [comment]
Oh sry! I put a broken link in `en/Dynamic Programming/Longest Common Subsequence.md`, I made the changes with a regex and I didn't notice it! in a moment I updated it

**Comment by Panquesito7** [comment]
Sorry for the long delay. I'll check this out tomorrow. Thanks. 🙂

**Comment by AnujSsStw** [comment]
hey @Panquesito7 while checking this you should also consider checking other links too like this c++ one and there are some more that I think I saw.
Capture1

**Review by Panquesito7 — APPROVED** [review]
Looks great. Thanks! 🚀


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Efficient

**Pull request merged**
