### PR TITLE
Update: Implementations Links added in Aliquot_Sum.md

### PR DESCRIPTION
**Pull request by chetannada**
Added Implementations Links in Aliquot_Sum.md

### Description

Closes #{ISSUE_ID} 

### Checklist

- [ ] A description of the changes in this PR is mentioned above.
- [ ] All the new and existing checks pass.
- [ ] No plagiarized, duplicated, or repetitive documentation that has been directly copied from another source.
- [ ] If it's a new explanation, it contains solid, understandable, and accessible information.
- [ ] I have read the whole [contributing guidelines](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/CONTRIBUTING.md) and agree to the [Code of Conduct](https://github.com/TheAlgorithms/.github/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by appgurueu — COMMENTED** [review]
Please replace the specific implementation links with one link to the TheAlgorithms site for the Aliquot sum. See https://github.com/TheAlgorithms/Algorithms-Explanation/issues/190.

**Comment by chetannada** [comment]
> Please replace the specific implementation links with one link to the TheAlgorithms site for the Aliquot sum. See #190.

Are you mean to say, i need to remove all implementation link and add only one link to the TheAlgorithms site for the Aliquot sum. For ex: `https://the-algorithms.com/algorithm/aliquot-sum`

Then what about the below links in website it self?
Aliquot Sum - The Algorithms

It will be replace by one link only after i'll replace to one link right? so it will show the same URL of the website when user will click on this implementation link.

Please confirm. What should i do! Thanks.

**Comment by appgurueu** [comment]
> Are you mean to say, i need to remove all implementation link and add only one link to the TheAlgorithms site for the Aliquot sum. For ex: https://the-algorithms.com/algorithm/aliquot-sum

Yes.

> so it will show the same URL of the website when user will click on this implementation link.

Indeed it will be a link to the same page the user is already on. This is a redundancy problem: The links are (presumably) there for when the explanations are viewed on GitHub, but on the website they are redundant. This is a website issue IMO.

**Comment by chetannada** [comment]
> > Are you mean to say, i need to remove all implementation link and add only one link to the TheAlgorithms site for the Aliquot sum. For ex: https://the-algorithms.com/algorithm/aliquot-sum
> 
> Yes.
> 
> > so it will show the same URL of the website when user will click on this implementation link.
> 
> Indeed it will be a link to the same page the user is already on. This is a redundancy problem: The links are (presumably) there for when the explanations are viewed on GitHub, but on the website they are redundant. This is a website issue IMO.

@appgurueu As per your suggestion, I added single link to the TheAlgorithms site for the Aliquot sum.

**Review by appgurueu — APPROVED** [review]
Though you could omit the `-Aliquot-Sum`

**Comment by chetannada** [comment]
> Though you could omit the `-Aliquot-Sum`

@appgurueu  Yeah, Sure i have omitted -Aliquot-Sum

**Review by appgurueu — APPROVED** [review]

**Comment by chetannada** [comment]
Hi @vbrazo and @Panquesito7 Please review this PR. Thanks.

**Review by Panquesito7 — APPROVED** [review]
Thank you! 🚀

**Pull request merged**
